package org.example.fix;

import org.example.model.*;
import org.example.util.Price;

import java.util.Map;

/**
 * Stateless adapter: translates FIX 4.4 tag-value maps into domain {@link Order}
 * objects.  Keeps FIX wire format (integer tag numbers) decoupled from the
 * core matching engine.
 * ---
 * Pattern: Adapter
 * Converts external FIX representation → internal domain model.
 * The engine never sees raw FIX tags.
 *---
 * Usage
 * Create one instance per instrument scale and reuse it:
 * {
 *   FixOrderAdapter adapter = new FixOrderAdapter(100);  // 2-decimal prices
 *   Order o = adapter.fromNewOrderSingle(nextOrderId(), fixFields);
 * }
 */
public class FixOrderAdapter {

    private static final int TAG_CL_ORD_ID    = 11;
    private static final int TAG_SYMBOL       = 55;
    private static final int TAG_SIDE         = 54;
    private static final int TAG_ORD_TYPE     = 40;
    private static final int TAG_ORDER_QTY    = 38;
    private static final int TAG_PRICE        = 44;
    private static final int TAG_TIME_IN_FORCE = 59;

    private final int priceScale;

    public FixOrderAdapter(int priceScale) {
        if (priceScale <= 0) {
            throw new IllegalArgumentException("priceScale must be positive");
        }
        this.priceScale = priceScale;
    }

    /**
     * Parse a FIX NewOrderSingle (MsgType D) into a domain Order.
     *
     * @param orderId internal order ID (generated by the engine)
     * @param fields  FIX tag → value map
     * @return domain Order
     */
    public Order fromNewOrderSingle(long orderId, Map<Integer, String> fields) {
        String    clOrdId  = requireTag(fields, TAG_CL_ORD_ID);
        String    symbol   = requireTag(fields, TAG_SYMBOL);
        Side      side     = Side.fromFixCode(requireTag(fields, TAG_SIDE).charAt(0));
        OrderType ordType  = OrderType.fromFixCode(requireTag(fields, TAG_ORD_TYPE).charAt(0));
        double    orderQty = Double.parseDouble(requireTag(fields, TAG_ORDER_QTY));

        Order.Builder builder = new Order.Builder(orderId, side, ordType, orderQty)
                .clOrdId(clOrdId)
                .symbol(symbol);

        if (ordType == OrderType.LIMIT) {
            double price = Double.parseDouble(requireTag(fields, TAG_PRICE));
            builder.price(Price.toLong(price, priceScale));
        }

        String tifStr = fields.get(TAG_TIME_IN_FORCE);
        if (tifStr != null && !tifStr.isEmpty()) {
            builder.timeInForce(TimeInForce.fromFixCode(tifStr.charAt(0)));
        }

        return builder.build();
    }

    private static String requireTag(Map<Integer, String> fields, int tag) {
        String value = fields.get(tag);
        if (value == null || value.isEmpty()) {
            throw new IllegalArgumentException("Missing required FIX tag: " + tag);
        }
        return value;
    }
}
